spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db05
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: test
    database: 0
  rabbitmq:
    host: localhost
    port: 15672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/