spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: false
  properties:
    hibernate: 
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
  redis:
    database: 0
    timeout: 6000
  messages:
    basename: messages,messages_system
    encoding: UTF-8
  cloud:
    mvc:
      token-relay: 
        enabled: false
    
eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true

server:
  port: 8081

micro-service:
  config-service-uri: lb://config-service
  user-service-uri: lb://user-service
  reserve-service-uri: lb://reserve-service
  hall-service-uri: lb://hall-service
  movie-service-uri: lb://movie-service
  system-service-uri: lb://system-service
  api-gateway-uri: lb://api-gateway
 
logging:
  level:
    com.se.movie.simple: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
    
lombok:
  anyConstructor:
    addConstructorProperties: true