spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: test
    database: 0
  rabbitmq:
    host: localhost
    port: 15672
    username: admin
    password: admin
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security.web: DEBUG